In [2]:
import numpy as np

## Questão 1 - Crie um numpy array com 10 elementos 0, exceto o elemento de índice 6, que deve ser 20

In [6]:
resposta = np.zeros(10)
resposta[6] = 20
resposta


array([ 0.,  0.,  0.,  0.,  0.,  0., 20.,  0.,  0.,  0.])

## Questão 2 - Crie uma função que receba um numpy array e retorne um array de 20 elementos contendo apenas o maior elemento do array recebido

In [25]:
def resposta(array):
    shape = array.shape
    maximo = array.max()
    return np.full (shape, maximo)

Mari = np.array([[1,2,800], [4,30,6], [7,8,9]])

resposta(Mari)

array([[800, 800, 800],
       [800, 800, 800],
       [800, 800, 800]])

## Questão 3 - Faça uma função que receba um array, eleve ele ao quadrado, some 3, pegue apenas o elementos que são diferentes de 4 e, por último, divida por 4. Depois, retorne esse array modificado

In [36]:
def resposta(array):
    array = (array**2) + 3
    return (array[array != 4])/4

resposta(np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]]))


array([ 1.75,  3.  ,  4.75,  7.  ,  9.75, 13.  , 16.75, 21.  , 25.75,
       31.  , 36.75])

## Questão 4 - Faça uma função que receba dois array, junte os dois e retorne

In [50]:
def concatenar(array, array_1):
    return np.concatenate((array, array_1), axis = None)

array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])

concatenar(array_1, array_2)


array([1, 2, 3, 4, 5, 6])

## Questão 5 - Faça uma função que descreva meu array exibindo os seguintes dados com até 3 casas decimais: máx, min, média, desvio padrão (standard deviation). A exibição deve ser da seguinte forma:

```
******************************
Array: [0, 5, 6, 8, 9]

Max: 9
Min: 0
Media: 5.6
Desvio padrao: 3.137
******************************
```

In [66]:
def relatorio(array):
    print('*'*40)
    print(f'Array: {array}')
    print('')
    print(f'Máximo: {array.max()}')
    print(f'Mínimo: {array.min()}')
    print(f'Média: {array.mean()}')
    print(f'Desvio Padrão: {array.std():,.3f}')
    print('*'*40)

array = np.array([0, 5, 6, 8, 9])

relatorio(array)

****************************************
Máximo: 9
Mínimo: 0
Média: 5.6
Desvio Padrão: 3.137
****************************************
